name: Deploy to Nexus
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  restorePassword:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - shell: bash
        env:
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_KEY_PSWD: ${{ secrets.KEYSTORE_KEY_PSWD }}
          KEYSTORE_PSWD: ${{ secrets.KEYSTORE_PSWD }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          OSSR_USERNAME: ${{ secrets.OSSR_USERNAME }}
          OSSR_PASSWORD: ${{ secrets.OSSR_PASSWORD }}
          SONATYPE_STATING_PROFILE_ID: ${{ secrets.SONATYPE_STATING_PROFILE_ID }}
        run: |
          pwd
          echo "${{ secrets.KEYSTORE_FILE }}" > keystore.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_FILE_PSWD }}" --batch keystore.asc > keystore
          echo "${{ secrets.GPG_FILE }}" > sec.gpg.asc
          gpg -d --passphrase "${{ secrets.GPG_FILE_PSWD }}" --batch sec.gpg.asc > sec.gpg
          fastlane deployNexus
