name: Deploy to Nexus
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  deployToNexus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - shell: bash
        env:
          # The following env variables are used by gradle/publish-module.gradle
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          # The following env variables are used by gradle/publish-root.gradle.kts
          OSSR_USERNAME: ${{ secrets.OSSR_USERNAME }}
          OSSR_PASSWORD: ${{ secrets.OSSR_PASSWORD }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
        # The script generates sec.gpg file that is required by gradle/publish-module.gradle
        # and starts :deployNexus lane using fastlane.
        run: |
          java --version
          echo "${{ secrets.GPG_FILE }}" > sec.gpg.asc
          gpg -d --passphrase "${{ secrets.GPG_FILE_PSWD }}" --batch sec.gpg.asc > sec.gpg
          fastlane deployNexus
      - name: Nexus release
        uses: Propromp/nexus-release@1
        with:
          server: "oss.sonatype.org"
          groupId: "no.nordicsemi.android.common" # Group id of the repository
          nexusUsername: ${{ secrets.OSSR_USERNAME }} # User name of the nexus repository manager
          nexusPassword: ${{ secrets.OSSR_PASSWORD }} # Password of the nexus repository manager
